### ISSUE TITLE
firefox: unsafe RTCSessionDescription shim

### ISSUE THREAD

**Issue by fippo** [twilio/twilio-webrtc.js#106]
from [stackoverflow](https://stackoverflow.com/questions/56729034/mozrtcsessiondescription-undefined/56739213)
```
module.exports = typeof RTCSessionDescription !== 'undefined'
  ? RTCSessionDescription
: mozRTCSessionDescription;
```
can go wrong if media.peerconnection.enabled is set to false in about:firefox.
The minimal modification here is probably to say `: window.mozRTCSessionDescription`

**Comment by graue** [comment]
There's a similar problem with a reference to `RTCPeerConnection`
