### ISSUE TITLE
Safari 10 support

### ISSUE THREAD

**Issue by as-eugene-s** [twilio/twilio-webrtc.js#20]
Hello!

Can I use this module as shim for Safari 10 to work with twilio-video.js ?

If yes - can you explain how to use it? I tried to replace `window.navigator.getUserMedia` and other instances with your exports and it still not work.

**Comment by rfbrazier** [comment]
Safari 10 does not support WebRTC. twilio-video.js requires WebRTC and
therefore works with Safari 11, Chrome and Firefox.

On Fri, Nov 17, 2017 at 04:45 as-eugene-s <notifications@github.com> wrote:

> Hello!
>
> Can I use this module as shim for Safari 10 to work with twilio-video.js ?
>
> If yes - can you explain how to use it? I tried to replace
> window.navigator.getUserMedia and other instances with your exports and
> it still not work.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twilio_twilio-2Dwebrtc.js_issues_20&d=DwMCaQ&c=x_Y1Lz9GyeGp2OvBCa_eow&r=g4LA7GVMZvyLENPBWHHJ2ET2KVbQd9nR8P1BJI3ADJo&m=tUhoML7eLcr1cKL7AkVFNg8jMwWm0Y46vS93QrlXw9o&s=cwF3PWyFH_7uhXoLO3KmaVPBU9BgUNnTLInFtmvo1S4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAHJj69YCv-5FFbxsHfVOGc-2DVDMXACVTZ-5Fks5s3X-5FtgaJpZM4Qh-5FRq&d=DwMCaQ&c=x_Y1Lz9GyeGp2OvBCa_eow&r=g4LA7GVMZvyLENPBWHHJ2ET2KVbQd9nR8P1BJI3ADJo&m=tUhoML7eLcr1cKL7AkVFNg8jMwWm0Y46vS93QrlXw9o&s=LmzZqQMLsdOOHZdluvEshOkiK81e09QhOjVngytobZQ&e=>
> .
>
-- 
------
Rob Brazier
Product Management, Twilio
m: (330) 419-0950

**Comment by markandrus** [comment]
Hi @as-eugene-s,

As @rfbrazier mentioned, this will not work with Safari 10. Also, this library is not really intended for general consumption. It’s a library we factored out of twilio-video.js
