### ISSUE TITLE
How to use webrtc ?

### ISSUE THREAD

**Issue by dineshmaths1** [twilio/twilio-webrtc.js#27]
Hii,
I want to implement on angular cli side. Its possible ? If its possible  give me the sample code.
Or any other flow to use webrtc on angular cli side.

**Comment by markandrus** [comment]
Hi, I don't recommend you use this library. This library provides WebRTC shims for [twilio-video.js](http://github.com/twilio/twilio-video.js). As far as sample code, this project is really just re-exporting the existing [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection) and related APIs. So, in your Angular app, you can just use the normal browser APIs.
